### ISSUE TITLE
Plugin running in Child Bridge, keeps restarting Child Bridge after update

### ISSUE THREAD

**Issue by TheNastyness** [EHylands/homebridge-boschcontrolpanel_bgseries#4]
Hey man - I've had great luck with this plugin ever since release!  I was doing some maintenance today on my Hombridge instance and was going through and updating various plugins.  I've got this plugin running in a Child Bridge.  After updating to the latest version today as well as updating UI X to 1.5.0, the child bridge process keeps restarting.  Any idea why this could be happening?  Let me know what log info you need.

**Comment by TheNastyness** [comment]
Here is the portion of the log detailing what is happening (with MAC address omitted):
[10/1/2022, 1:52:35 PM] [homebridge-boschcontrolpanel_bgseries] Launched child bridge with PID 2142
[10/1/2022, 1:52:35 PM] Registering platform 'homebridge-boschcontrolpanel_bgseries.BoschControlPanel_BGSeries'
[10/1/2022, 1:52:35 PM] [homebridge-boschcontrolpanel_bgseries] Loaded homebridge-boschcontrolpanel_bgseries v0.5.2 child bridge successfully
[10/1/2022, 1:52:35 PM] Loaded 5 cached accessories from cachedAccessories.xxxxxxxxxxxx.
[10/1/2022, 1:52:35 PM] Publishing bridge accessory (name: homebridge-boschcontrolpanel_bgseries, publishInfo: {
  username: 'xx:xx:xx:xx:xx:xx',
  port: 45632,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[10/1/2022, 1:52:35 PM] Homebridge v1.5.0 (HAP v0.10.2) (homebridge-boschcontrolpanel_bgseries) is running on port 45632.
TypeError: Cannot set property 'PointText' of undefined
    at BGController.ReadMode2ReqPointText_CF03 (/usr/local/lib/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGController.ts:1271:28)
    at BGController.ReadProtocolMessage_0x01 (/usr/local/lib/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGController.ts:516:20)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGController.ts:220:18)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
    at Socket.ondata (internal/js_stream_socket.js:77:22)
    at Socket.emit (events.js:400:28)
[10/1/2022, 1:52:49 PM] [homebridge-boschcontrolpanel_bgseries] Child bridge process ended
[10/1/2022, 1:52:49 PM] [homebridge-boschcontrolpanel_bgseries] Process Ended. Code: 1, Signal: null
[10/1/2022, 1:52:56 PM] [homebridge-boschcontrolpanel_bgseries] Restarting Process...

**Comment by EHylands** [comment]
Will look into that right now.
Can you try choosing "Force Legacy Mode" to see if tou get the same error ?

**Comment by TheNastyness** [comment]
Thank you for the quick reply.  It seems that turning on "Force Legacy Mode" did indeed fix it.  I don't want to be running in Legacy mode though, do I?  I've got a B8512G panel.

**Comment by EHylands** [comment]
Legacy mode sends one packet for each point to get PointText (Very Slow) while "Regular Mode" gets multiple PointText for every packet.

Legacy Mode was only to pin point error location.

Please disable Legacy Mode
In plugin configuration (in UI X), please install plugin alternate version 0.5.3 beta.
Log file will provide more information to further access error.

**Comment by EHylands** [comment]
I did some further testing:
I was able to reproduce similar errors if a Point source was set to Output or Wireless with an unassigned point profile.
I dont have any wireless point, point monitoring output or ip cam. I missed that particular situation.
I hope version 0.5.3 beta will fix the issue.

**Comment by TheNastyness** [comment]
0.5.3 beta seems to have resolved it, I've got Force Legacy Mode turned off and it's working fine.

I do have wireless devices on points 9 and 10, but neither have unassigned point profiles.  I do have a hardwired point that isn't being used... Hardwired point 8 was previously a water leak detector which was replaced by a HK native device.  This point has a unique name - "Basement Flood Sensor" but has an unassigned point profile.  Offering up this info in case it might help you troubleshoot?

Anyway - thank you for the quick fix, everything is working fine now!

**Comment by TheNastyness** [comment]
One other quick note, now that I have updated to 0.5.3 beta, I'm seeing Panel Confidence Messages in the Homebridge log even though I do not have this box checked in the plugin settings.

**Comment by EHylands** [comment]
Thank you for the information.
Unassigned point profile was a situation I did not considered while rewriting some inner components of the controller.

I will issue a new release with the current fix.

Are you still running Homebridge in debug mode ? Confidence message are shown in debug mode.

**Comment by TheNastyness** [comment]
Yes I’m in debug mode. Interestingly, while on 0.5.2, confidence messages didn’t show up in the logs with debug turned ON. I was in Legacy mode at that time per your recommendation.

**Comment by EHylands** [comment]
There are no panel confidence message packet in legacy mode since the plugin is regularly pooling the panel rather than waiting for notifications (subscriptions).

**Comment by TheNastyness** [comment]
Got it.
