### ISSUE TITLE
Solution 3000 - No Area/Point text when no outputs are configured on panel

### ISSUE THREAD

**Issue by renkoh** [EHylands/homebridge-boschcontrolpanel_bgseries#9]
Have recenly done a new install, a Solution 3000 + B426 ethernet module. It is using the recently release v2.1.0.0 firmware.

I am getting no area names and no point names (have not configured outputs yet)

```
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Bosch Control Panel Information
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Type: Solution3000
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] RPS Version: 5.2.0
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Intrusion Protocol Version: 5.23.0
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Execute Protocol Version: 2.22.0
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Max Areas: 2
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Max Points: 16
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Max Outputs: 3
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Max Users: 32
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Max Keypads: 4
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Max Doors: 0
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Panel Legacy Mode: true
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Area1: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point1: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point2: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point3: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point4: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point5: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point6: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point7: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point8: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point9: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point10: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries]   Point16: 
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] Configuring Homebridge plugin accessories
[1/2/2023, 1:15:16 AM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:71:9)
    at HB_BoschControlPanel_BGSeries.DiscoverAreas (/homebridge/node_modules/homebridge-boschcontrolpanel_bgseries/src/platform.ts:237:27)
    at BGController.<anonymous> (/homebridge/node_modules/homebridge-boschcontrolpanel_bgseries/src/platform.ts:318:14)
    at BGController.emit (node:events:527:28)
    at BGController.SendMode2ReqOutputText_CF01 (/homebridge/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGController.ts:1353:16)
    at BGController.ReadProtocolMessage_0x01 (/homebridge/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGController.ts:538:20)
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGController.ts:229:18)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    ```

Not sure if I am doing something wrong, but the names are definitely defined on the panel.

If you need more info, happy to provide.

**Comment by EHylands** [comment]
Hi,
When was that new firmware released ?
Intrusion and execute version protocols looks to be the same than previously reported by another user in November. 

Are you using alternate language on your board ?

The are unfortunately no official documentation from Bosch AU on which part of the official protocol at is supported on Solution panels.

Are you running Homebridge in debug mode ?

Tnx !

`[20/11/2022, 10:34:33 am] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge 0A45) is running on port 51026.
[20/11/2022, 10:34:45 am] [BoschControlPanel_BGSeries] -----------------------------------------
[20/11/2022, 10:34:45 am] [BoschControlPanel_BGSeries] Bosch Control Panel Information
[20/11/2022, 10:34:45 am] [BoschControlPanel_BGSeries] -----------------------------------------
[20/11/2022, 10:34:45 am] [BoschControlPanel_BGSeries] Panel Type: Solution3000
[20/11/2022, 10:34:45 am] [BoschControlPanel_BGSeries] RPS Version: 5.2.0
[20/11/2022, 10:34:45 am] [BoschControlPanel_BGSeries] Intrusion Protocol Version: 5.23.0
[20/11/2022, 10:34:45 am] [BoschControlPanel_BGSeries] Execute Protocol Version: 2.22.0`

**Comment by EHylands** [comment]
New firmware was released on Dec 23rd !

Will ask Brendon in other thread if he has same experience as you with new firmware.

Let's hope they've add subscriptions notifications and recent command format fonction in new firmware !

**Comment by renkoh** [comment]
Thanks. I might downgrade to 2.0.5.0 and see if its something on my end, will report back

**Comment by EHylands** [comment]
I honestly didn't plan for the situation where Area,Point or Output would not a name string.
Please install alternate beta version 0.6.7.
I think you will be able to operate plugin this way whitout accessory official name.

We can troubleshoot after why panel is not providing item name string.
Bosch AU technical support doesn't think any changes were made to the automation protocol.
He will get back to me after holidays.

**Comment by renkoh** [comment]
Thanks, let me try that. 

I might have a play around and see what I can get working, too. I am a TS dev but still pretty new to homebridge plugins

**Comment by renkoh** [comment]
Interestingly, the names come through when polling for the points/areas (I think)

```
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Bosch Control Panel Information
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Type: Solution3000
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] RPS Version: 5.2.0
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Intrusion Protocol Version: 5.23.0
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Execute Protocol Version: 2.22.0
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Max Areas: 2
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Max Points: 16
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Max Outputs: 3
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Max Users: 32
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Max Keypads: 4
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Max Doors: 0
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Panel Legacy Mode: true
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Area1: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point1: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point2: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point3: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point4: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point5: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point6: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point7: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point8: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point9: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point10: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries]   Point16: 
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Configuring Homebridge plugin accessories
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Security System: Area1 - Area1
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] ContactSensor : Point1 - Pointundefined
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] Starting Control Panel Operation
[1/2/2023, 12:06:30 PM] [homebridge-boschcontrolpanel_bgseries] -----------------------------------------
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point1(Front Door): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point2(Sitting Room): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point3(Hallway): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point4(Dining): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point5(Lounge): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point6(Master Bed): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point7(Study): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point8(Retreat): Open
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point9(Laundry): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point10(Lounge): Normal
[1/2/2023, 12:06:38 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Point16(Tamper): Normal
[1/2/2023, 12:06:39 PM] [homebridge-boschcontrolpanel_bgseries] Panel: Area1(AREA1): Disarmed
```

**Comment by EHylands** [comment]
The plugin only reads Area, Point and Output text at startup.
The problem is in my plugin.
Since you don't have any configured outputs, it prematurely starts controller operation before finishing reading all area and point text.
Will fix this error and report back to you.

**Comment by EHylands** [comment]
Please try alternate beta version 0.6.8

**Comment by EHylands** [comment]
Hi @renkoh 
Were you able to test latest version 0.6.8 ?

**Comment by renkoh** [comment]
Hi sorry, yes I am using it now and it seems to be working okay!
